config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  resources :developers do
    resources :games
  end
  resources :fans, :games
  root 'static_pages#home'
  get 'tally', to: 'static_pages#tally'
  get 'order', to: 'static_pages#order'
  get '/auth/github/callback' => 'sessions#create'
  get 'jsindex', to: 'static_pages#jsindex'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :games
  has_many :fans, through: :games
  has_secure_password

  validates :name, presence: true, uniqueness: true
  validates :employees, presence: true,  numericality: { greater_than: 0 } 
  validates :location, presence: true
  validates :password, presence: true, length: {within: 5..30}

  def self.from_omniauth(auth)
    where(uid: auth.uid).first_or_initialize.tap do |dev|
      dev.id = auth.uid 
      dev.password = 'tester'
      dev.name = 'GithubProfile'
      dev.employees = 1
      dev.location = 'GitHub'
      dev.save!
    end
  end

  def self.order_by_number_of_games
    self.joins(:games)
    .group("developers.id")
    .order('COUNT(games.id) DESC')
  end
end

app/models/fan.rb
class Fan < ApplicationRecord
  has_one :game
  has_many :developers, through: :games

  validates :name, presence: true
  validates :game_id, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :developer
  has_many :fans

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :genre, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_dev

  def current_dev
    session[:dev_id].nil? ? nil : Developer.find(session[:dev_id])
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_developer, only: [:show, :edit, :update, :destroy]

  def new
    @developer = Developer.new
  end

  def create
    @developer = Developer.new(developer_params)
    if @developer.save
      session[:dev_id] = @developer.id
      redirect_to developer_path(@developer)
    else
      render :new
    end
  end

  def show
    @message = params[:message] if params[:message]
    @message ||= false
    if session[:dev_id]
      @games = @developer.games
    else
      redirect_to login_path
    end
  end

  def index
    @developers = Developer.all
  end

  def edit
  end

  private

    def set_developer
      @developer = Developer.find(params[:id])
    end

    def developer_params
      params.require(:developer).permit(
        :name,
        :employees,
        :location,
        :password,
        :password_confirmation
      )
    end
end

app/controllers/fans_controller.rb
class FansController < ApplicationController
  def new
    @fan = Fan.new
  end

  def create
    @fan = Fan.new(fan_params)
    respond_to do |format|
      if @fan.save
        format.html { redirect_to '/tally', notice: 'Fan was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @fan = Fan.find(params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @fan}
    end
  end

  def index
    @fans = Fan.all
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @fans}
    end
  end

  def edit
  end

  private

  def fan_params
    params.require(:fan).permit(:name, :game_id)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new(developer_id: params[:developer_id])
  end

  def create
    @game = Game.new(game_params)
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @game = Game.find(params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @game}
    end
  end

  def index
    if params[:developer_id]
      @games = Developer.find(params[:developer_id]).games
      respond_to do |format|
				format.html {render :index}
				format.json {render json: @games}
			end
    else
      @games = Game.all
      respond_to do |format|
				format.html {render :index}
				format.json {render json: @games}
			end
    end
  end

  private

  def game_params
    params.require(:game).permit(:title, :description, :genre, :price, :developer_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session.destroy
    redirect_to '/'
  end

  def new
    @dev = Developer.new
    @devs = Developer.all
  end

  def create
    # w/ OAUTH 
    if auth_hash = request.env["omniauth.auth"]
      @dev = Developer.from_omniauth(request.env["omniauth.auth"])
      if @dev.valid?
        session[:dev_id] = @dev.id
      end
    end
    if session[:dev_id] == nil # If session does not exist must be regular login
      @dev = Developer.find_by(id: params[:developer][:id])
    end
    if @dev.name == 'GithubProfile'
      redirect_to tally_path
    elsif @dev && @dev.authenticate(params[:developer][:password])
      session[:dev_id] = @dev.id
      redirect_to @dev
    else
      redirect_to '/login'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def tally
    @games = Game.all
    @devs = Developer.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developer_helper.rb
module DeveloperHelper
end

app/helpers/fan_helper.rb
module FanHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/developers/_form.html.erb
<%= form_for @developer do |f| %>
  <% if @developer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@developer.errors.count, "error") %> prohibited this Developer from being saved:
      </h2>

      <ul>
        <% @developer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="form-group">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :employees, "How many employees?" %>
    <br>
    <%= f.number_field :employees, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :location, "Location" %>
    <br>
    <%= f.text_field :location, class: "form-control" %>
  </div>

  <%= f.label :password %>
  <br>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <br>
  <%= f.password_field :password_confirmation %>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/developers/create.html.erb
<h1>Developer#create</h1>
<p>Find me in app/views/developer/create.html.erb</p>

app/views/developers/edit.html.erb
<h1>Developer#edit</h1>
<p>Find me in app/views/developer/edit.html.erb</p>

app/views/developers/index.html.erb
<h1>Developer Index</h1>
<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><strong>Name</strong></td>
      <td><strong>Employees</strong></td>
      <td><strong>Location</strong></td>
    </tr>
    <% @developers.each do |developer| %>
      <tr>
    
        <td><%= link_to "#{developer.name}", developer_path(developer) %></td>
        <td><%= developer.employees %></td>
        <td><%= developer.location %></td>
        <% end %>
      </tr>
  </tbody>
</table>
<br> <br>
<%= link_to "Back to Home", '/' %>

app/views/developers/new.html.erb
<h1>Developer Registration</h1>
<%= render 'form' %>
<br> <br>
<%= link_to "Back to Home", '/' %>

app/views/developers/show.html.erb
<h1><%= @developer.name %></h1>
<p id="notice"><%= notice %></p>
<% if @message %>
  <div class="center alert">
    <p><%= @message %></p>
  </div>
<% end %>
<div class="center">
  <div class="info">
    <p><strong>Name:</strong> <%= @developer.name %></p>
    <p><strong>Employees:</strong> <%= @developer.employees %></p>
    <p><strong>Location:</strong>  <%= @developer.location %></p>
    <% @games.each do |game| %>
      <p>
        <%= link_to "#{game.title}", game_path(game) %>
      </p> 
    <% end %>
    <br>
    <%= link_to "Add Game", new_developer_game_path(@developer) %>
  </div>
  <br>
  <%= link_to "Return to Developer Index", developers_path %>
</div>

app/views/fans/_form.html.erb
<%= form_for(@fan) do |f| %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %></div

  <div class="form-group">
    <%= f.label "Vote for your favorite Game" %>   
    <%= f.collection_select(:game_id, Game.all, :id, :title)%>
   <br>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/fans/index.html.erb
<h1>Fans Index</h1>
<table class="table">
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><strong>Fan Name</strong></td>
      <td><strong>Game Choice</strong></td>
    </tr>
    <% @fans.each do |fan| %>
      <tr>
        <td><%= link_to "#{fan.name}", fan_path(fan) %></td>
        <td><%= fan.game_id %></td>
        <% end %>
      </tr>
  </tbody>
</table>
<br> <br>
<%= link_to "Back to Home", '/' %>

app/views/fans/new.html.erb
<h1>New Fan Page</h1>
<%= render 'form' %>
<br> <br>
<%= link_to "Back to Home", '/' %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>

  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@game.errors.count, "error") %> prohibited this user from being saved:
      </h2>

      <ul>
        <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %></div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %></div>
    
  <div class="form-group">
    <%= f.label :genre %>
    <%= f.text_field :genre, class: "form-control" %></div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %></div>

    <%= f.hidden_field :developer_id, value: params[:developer_id] %>

  <div class="actions">
    <%= f.submit "Create Game" %>
  </div>
<% end %>

app/views/games/create.html.erb
<h1>Game#create</h1>
<p>Find me in app/views/game/create.html.erb</p>

app/views/games/index.html.erb
<h1>Games Index</h1>
<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><strong>Title</strong></td>
      <td><strong>Genre</strong></td>
      <td><strong>Price</strong></td>
      <td><strong>Developer</strong></td>
    </tr>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to "#{game.title}", game_path(game) %></td>
        <td><%= game.genre %></td>
        <td><%= game.price %></td>
        <td><%= game.developer.name %></td>
        <% end %>
      </tr>
  </tbody>
</table>
<br> <br>
<%= link_to "Back to Home", '/' %>

app/views/games/new.html.erb
<h1>Create a New Game for <%= @game.developer.name %></h1>
<%= render 'form' %>

app/views/games/show.html.erb
<h1><%= @game.title %></h1>
<p id="notice"><%= notice %></p>
<% if @message %>
  <div class="center alert">
    <p><%= @message %></p>
  </div>
<% end %>
<div class="center">
  <div class="info">
  
    <p><strong>Title:</strong> <%= @game.title %></p>
    <p><strong>Description:</strong> <%= @game.description %></p>
    <p><strong>Genre:</strong>  <%= @game.genre %></p>
    <p><strong>Price:</strong>  <%= @game.price %></p>
    <p><strong>Developer: </string><%= link_to "#{@game.developer.name}", developer_path(@game.developer) %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GamefanManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id='main-display-div'></div>  
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Game Fan Manager Welcomes You</h1>
<%= link_to "Login Developer", '/login' %> <br>
<%= link_to "Register Developer", new_developer_path, class: "btn btn-primary" %> <br>
<%= link_to "Index Developers", developers_path, class: "btn btn-primary" %> <br>
<%= link_to "Index Games", games_path, class: "btn btn-primary" %> <br>
<%= link_to "Index Fans", fans_path%> <br>
<br>
<%= link_to "Game Fans Vote Here!", new_fan_path, class: "btn btn-primary" %> <br>
<%= link_to "Current Vote Tally", 'tally'%>
<br>
<%= link_to "Class Method Test", 'order'%>
<br> <br>
<%= link_to "JavaScript Index Test", 'jsindex'%>

<br> <br>
<% if session[:dev_id] %>
  <%= link_to "Log out", logout_path, method: :delete %>   
<% end %>

app/views/static_pages/jsindex.html.erb
<h1>JS Index</h1>
<button id="js_index_games">Index All Games w/ AJAX</button>
<br> <br>
<button id="js_show_game">Show Game w/ AJAX</button>
<br> <br>
<button id="js_freeholder_fans">Show Fans of FreeHolder w/ AJAX</button>
<br> <br>
<%= link_to "Back to Home", '/' %>

app/views/static_pages/order.html.erb
<h1> Developers by Number of Games </h1>
<table class="table">
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>Name</strong></td>
      <td><strong>Game Count</strong></td>
    </tr>
    <% Developer.order_by_number_of_games.each do |dev_id| %>
      <tr>
        <td><%= link_to "#{Developer.find_by(id: dev_id).name}", developer_path(Developer.find_by(id: dev_id)) %></td>
        <td><%= "#{dev_id.games.count}" %></td>
        <% end %>
      </tr>
  </tbody>
</table>
<br> <br>
<%= link_to "Back to Home", '/' %>

app/views/static_pages/tally.html.erb
<h1>Fan Tally</h1>
<h2>Games</h2>
<table class="table">
  <thead>
    <tr>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><strong>Title</strong></td>
      <td><strong>Fans</strong></td>
      <td><strong>Genre</strong></td>
      <td><strong>Price</strong></td>
      <td><strong>Developer</strong></td>
    </tr>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to "#{game.title}", game_path(game) %></td>
        <td><%= game.fans.count %></td>
        <td><%= game.genre %></td>
        <td><%= game.price %></td>
        <td><%= link_to "#{game.developer.name}", developer_path(game.developer) %></td>
        <% end %>
      </tr>
  </tbody>
</table>
<h2>Developers</h2>
<table class="table">
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>Name</strong></td>
      <td><strong>Fans</strong></td>
    </tr>
    <% @devs.each do |dev| %>
      <tr>
        <td><%= link_to "#{dev.name}", developer_path(dev) %></td>
        <td><%= dev.fans.count %></td>
        <% end %>
      </tr>
  </tbody>
</table>
<br> <br>
<%= link_to "Back to Home", '/' %>